import type {
  CD,
  ColetaTms,
  ConfiguracaoPallets,
  ContagemItem,
  EmpresaSku,
  FaturaServico,
  Integracao,
  Onda,
  Owner,
  Pedido,
  PosicaoEstoque,
  Recebimento,
  Romaneio,
  SkuControle,
  SkuControleHistorico,
  Tarefa,
  ViagemEtiquetagem,
} from './types'
import {
  DEMO_OPERATIONAL_EVENTS,
  DEMO_OPERATIONAL_OCCURRENCES,
} from '../../../wms-shared-demo'
import type {
  OperationalEvent,
  OperationalOccurrence,
} from './types'
import {
  ADMIN_BUSINESS_DOCAS,
  ADMIN_BUSINESS_ENDERECOS_SUGESTOES,
  ADMIN_BUSINESS_PUTAWAY,
} from './adminBusinessLocations'

export const CDS: CD[] = [
  { id: 'cd-sp', nome: 'CD Cajamar', uf: 'SP' },
  { id: 'cd-rj', nome: 'CD Duque de Caxias', uf: 'RJ' },
  { id: 'cd-pe', nome: 'CD Jaboatão', uf: 'PE' },
]

export const OWNERS: Owner[] = [
  { id: 'own-all', nome: 'Todos os clientes', cor: '#64748b' },
  { id: 'own-nano', nome: 'NanoTech Eletrônicos', cor: '#2563eb' },
  { id: 'own-bella', nome: 'Bella Cosméticos', cor: '#db2777' },
  { id: 'own-verde', nome: 'Verde Alimentos', cor: '#16a34a' },
  { id: 'own-forte', nome: 'Forte Indústria', cor: '#f97316' },
]

export const ownerName = (id: string) =>
  OWNERS.find((o) => o.id === id)?.nome ?? '—'
export const ownerColor = (id: string) =>
  OWNERS.find((o) => o.id === id)?.cor ?? '#64748b'

export const EMPRESAS_SKU: EmpresaSku[] = [
  { id: 'emp-todas', nome: 'Todas as empresas', cor: '#64748b' },
  { id: 'emp-eletrolux', nome: 'EletroLux', cor: '#0f766e' },
  { id: 'emp-magazine-luiza', nome: 'MagazineLuiza', cor: '#2563eb' },
  { id: 'emp-casas-bahia', nome: 'Casas Bahia', cor: '#dc2626' },
  { id: 'emp-carrefour', nome: 'Carrefour', cor: '#7c3aed' },
]

export const empresaSkuName = (id: string) =>
  EMPRESAS_SKU.find((empresa) => empresa.id === id)?.nome ?? 'â€”'
export const empresaSkuColor = (id: string) =>
  EMPRESAS_SKU.find((empresa) => empresa.id === id)?.cor ?? '#64748b'

export const empresaSkuIdPorOwner = (ownerId: string) => {
  const porOwner: Record<string, string> = {
    'own-nano': 'emp-eletrolux',
    'own-bella': 'emp-magazine-luiza',
    'own-verde': 'emp-carrefour',
    'own-forte': 'emp-casas-bahia',
  }
  return porOwner[ownerId] ?? 'emp-eletrolux'
}

type SkuControleSeedInput = Omit<
  SkuControle,
  'empresaId' | 'cubagemM3' | 'criadoPor' | 'criadoEm' | 'atualizadoPor' | 'atualizadoEm'
> & {
  empresaId?: string
  criadoPor?: string
  criadoEm?: string
  atualizadoPor?: string
  atualizadoEm?: string
}

const cubagemSku = (comprimentoCm: number, larguraCm: number, alturaCm: number) =>
  Number(((comprimentoCm * larguraCm * alturaCm) / 1_000_000).toFixed(6))

const skuControleSeed = (input: SkuControleSeedInput): SkuControle => {
  const {
    criadoPor = 'Sistema seed',
    criadoEm = '2026-06-26T07:00:00.000Z',
    atualizadoPor = criadoPor,
    atualizadoEm = criadoEm,
    ...sku
  } = input

  return {
    ...sku,
    empresaId: sku.empresaId ?? empresaSkuIdPorOwner(sku.ownerId),
    cubagemM3: cubagemSku(sku.comprimentoCm, sku.larguraCm, sku.alturaCm),
    criadoPor,
    criadoEm,
    atualizadoPor,
    atualizadoEm,
  }
}

const SKU_CONTROLE_COMPLEMENTAR: SkuControle[] = [
  skuControleSeed({ id: 'sku-ctrl-1006', ownerId: 'own-nano', codigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 8, larguraCm: 4, alturaCm: 6 }),
  skuControleSeed({ id: 'sku-ctrl-1007', ownerId: 'own-nano', codigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 12, larguraCm: 2, alturaCm: 14 }),
  skuControleSeed({ id: 'sku-ctrl-1008', ownerId: 'own-nano', codigo: 'SKU-10244', descricao: 'Power Bank 10000mAh', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 14, larguraCm: 7, alturaCm: 2 }),
  skuControleSeed({ id: 'sku-ctrl-1009', ownerId: 'own-nano', codigo: 'SKU-10245', descricao: 'Suporte Veicular Magnético', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 7, larguraCm: 5, alturaCm: 9 }),
  skuControleSeed({ id: 'sku-ctrl-1010', ownerId: 'own-nano', codigo: 'SKU-10246', descricao: 'Hub USB-C 7 portas', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 12, larguraCm: 6, alturaCm: 2.5 }),
  skuControleSeed({ id: 'sku-ctrl-1011', ownerId: 'own-nano', codigo: 'SKU-10247', descricao: 'Mouse Vertical Pro', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 12, larguraCm: 8, alturaCm: 7 }),
  skuControleSeed({ id: 'sku-ctrl-1012', ownerId: 'own-nano', codigo: 'SKU-10248', descricao: 'Teclado Mecânico Compacto', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 32, larguraCm: 14, alturaCm: 4 }),
  skuControleSeed({ id: 'sku-ctrl-1013', ownerId: 'own-nano', codigo: 'SKU-10249', descricao: 'Webcam Full HD', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 9, larguraCm: 7, alturaCm: 6 }),
  skuControleSeed({ id: 'sku-ctrl-1014', ownerId: 'own-nano', codigo: 'SKU-10250', descricao: 'Cabo HDMI 2m', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 14, larguraCm: 3, alturaCm: 16 }),
  skuControleSeed({ id: 'sku-ctrl-1015', ownerId: 'own-nano', codigo: 'SKU-10251', descricao: 'Dock Station USB-C', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 16, larguraCm: 8, alturaCm: 3 }),
  skuControleSeed({ id: 'sku-ctrl-1016', ownerId: 'own-bella', codigo: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 4, larguraCm: 4, alturaCm: 11 }),
  skuControleSeed({ id: 'sku-ctrl-1017', ownerId: 'own-bella', codigo: 'SKU-20057', descricao: 'Batom Matte Rubi', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 2, larguraCm: 2, alturaCm: 9 }),
  skuControleSeed({ id: 'sku-ctrl-1018', ownerId: 'own-bella', codigo: 'SKU-20058', descricao: 'Máscara Facial Hidratação', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 8, larguraCm: 3, alturaCm: 13 }),
  skuControleSeed({ id: 'sku-ctrl-1019', ownerId: 'own-bella', codigo: 'SKU-20059', descricao: 'Creme Hidratante 200ml', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 6, larguraCm: 6, alturaCm: 15 }),
  skuControleSeed({ id: 'sku-ctrl-1020', ownerId: 'own-bella', codigo: 'SKU-20060', descricao: 'Água Micelar 120ml', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 5, larguraCm: 5, alturaCm: 14 }),
  skuControleSeed({ id: 'sku-ctrl-1021', ownerId: 'own-bella', codigo: 'SKU-20061', descricao: 'Protetor Solar FPS 50', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 5, larguraCm: 3, alturaCm: 14 }),
  skuControleSeed({ id: 'sku-ctrl-1022', ownerId: 'own-verde', codigo: 'SKU-30012', descricao: 'Grão de Bico 1kg', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 12, larguraCm: 7, alturaCm: 20 }),
  skuControleSeed({ id: 'sku-ctrl-1023', ownerId: 'own-verde', codigo: 'SKU-30013', descricao: 'Molho de Tomate Orgânico 340g', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 7, larguraCm: 7, alturaCm: 12 }),
  skuControleSeed({ id: 'sku-ctrl-1024', ownerId: 'own-verde', codigo: 'SKU-30014', descricao: 'Farinha Integral 1kg', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 14, larguraCm: 8, alturaCm: 22 }),
  skuControleSeed({ id: 'sku-ctrl-1025', ownerId: 'own-verde', codigo: 'SKU-30015', descricao: 'Granola Castanhas 500g', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 18, larguraCm: 8, alturaCm: 26 }),
  skuControleSeed({ id: 'sku-ctrl-1026', ownerId: 'own-verde', codigo: 'SKU-30016', descricao: 'Mix de Castanhas 250g', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 16, larguraCm: 6, alturaCm: 22 }),
  skuControleSeed({ id: 'sku-ctrl-1027', ownerId: 'own-verde', codigo: 'SKU-30017', descricao: 'Chá Verde 30g', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 8, larguraCm: 4, alturaCm: 13 }),
  skuControleSeed({ id: 'sku-ctrl-1028', ownerId: 'own-forte', codigo: 'MP-7781', descricao: 'Resina PET grau A', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 60, larguraCm: 40, alturaCm: 12 }),
  skuControleSeed({ id: 'sku-ctrl-1029', ownerId: 'own-forte', codigo: 'MP-7782', descricao: 'Pigmento Azul 04', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 30, larguraCm: 25, alturaCm: 18 }),
  skuControleSeed({ id: 'sku-ctrl-1030', ownerId: 'own-forte', codigo: 'MP-7784', descricao: 'Aditivo antiestático', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 35, larguraCm: 25, alturaCm: 22 }),
  skuControleSeed({ id: 'sku-ctrl-1031', ownerId: 'own-forte', codigo: 'MP-7785', descricao: 'Masterbatch Preto', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 40, larguraCm: 30, alturaCm: 20 }),
  skuControleSeed({ id: 'sku-ctrl-1032', ownerId: 'own-forte', codigo: 'MP-7790', descricao: 'Filme Stretch Industrial', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 50, larguraCm: 50, alturaCm: 12 }),
  skuControleSeed({ id: 'sku-ctrl-1033', ownerId: 'own-forte', codigo: 'MP-7791', descricao: 'Tampa Injetada Natural', tipo: 'unidade', skuUnidadeConteudo: null, unidadesPorCaixa: null, comprimentoCm: 60, larguraCm: 40, alturaCm: 35 }),
  skuControleSeed({ id: 'sku-ctrl-1034', ownerId: 'own-nano', codigo: 'CX-10242-10', descricao: 'Caixa matriz · Carregador Turbo 30W c/ 10 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'SKU-10242', unidadesPorCaixa: 10, comprimentoCm: 26, larguraCm: 18, alturaCm: 14 }),
  skuControleSeed({ id: 'sku-ctrl-1035', ownerId: 'own-nano', codigo: 'CX-10243-25', descricao: 'Caixa matriz · Cabo USB-C 2m c/ 25 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'SKU-10243', unidadesPorCaixa: 25, comprimentoCm: 32, larguraCm: 22, alturaCm: 18 }),
  skuControleSeed({ id: 'sku-ctrl-1036', ownerId: 'own-nano', codigo: 'CX-10244-04', descricao: 'Caixa matriz · Power Bank 10000mAh c/ 4 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'SKU-10244', unidadesPorCaixa: 4, comprimentoCm: 18, larguraCm: 15, alturaCm: 8 }),
  skuControleSeed({ id: 'sku-ctrl-1037', ownerId: 'own-bella', codigo: 'CX-20056-06', descricao: 'Caixa matriz · Base Líquida Tom 02 c/ 6 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'SKU-20056', unidadesPorCaixa: 6, comprimentoCm: 18, larguraCm: 12, alturaCm: 13 }),
  skuControleSeed({ id: 'sku-ctrl-1038', ownerId: 'own-verde', codigo: 'CX-30012-12', descricao: 'Caixa matriz · Grão de Bico 1kg c/ 12 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'SKU-30012', unidadesPorCaixa: 12, comprimentoCm: 40, larguraCm: 28, alturaCm: 24 }),
  skuControleSeed({ id: 'sku-ctrl-1039', ownerId: 'own-forte', codigo: 'CX-MP7784-08', descricao: 'Caixa matriz · Aditivo antiestático c/ 8 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'MP-7784', unidadesPorCaixa: 8, comprimentoCm: 45, larguraCm: 35, alturaCm: 30 }),
  skuControleSeed({ id: 'sku-ctrl-1040', ownerId: 'own-forte', codigo: 'CX-MP7785-11', descricao: 'Caixa matriz · Masterbatch Preto c/ 11 un', tipo: 'caixa-matriz', skuUnidadeConteudo: 'MP-7785', unidadesPorCaixa: 11, comprimentoCm: 50, larguraCm: 38, alturaCm: 32 }),
]

const SKU_CONTROLE_COMPLEMENTAR_HISTORICO: SkuControleHistorico[] = SKU_CONTROLE_COMPLEMENTAR.map((sku, index) => ({
  id: `sku-hist-${1101 + index}`,
  skuId: sku.id,
  skuCodigo: sku.codigo,
  acao: 'criacao',
  usuario: sku.criadoPor,
  quando: sku.criadoEm,
  resumo: 'SKU carregado no seed de 26/06/2026 para liberar recebimento e etiquetagem.',
  alteracoes: [
    { campo: 'Tipo', antes: '—', depois: sku.tipo === 'caixa-matriz' ? 'Caixa matriz' : 'Unidade' },
    { campo: 'Cubagem', antes: '—', depois: `${sku.cubagemM3.toLocaleString('pt-BR', { minimumFractionDigits: 6, maximumFractionDigits: 6 })} m³` },
  ],
}))

export const KPIS = {
  acuracidade: 99.4,
  produtividade: 142,
  otif: 97.8,
  ocupacao: 81,
  dockToStock: 2.4,
  divergencia: 0.6,
  cicloPedido: 3.1,
}

export const CONFIGURACAO_PALLETS: ConfiguracaoPallets = {
  total: 18,
  minimoLivre: 4,
  atualizadoPor: 'Supervisor demo',
  atualizadoEm: '2026-06-26T08:00:00.000Z',
}

export const OCORRENCIAS_OPERACIONAIS: OperationalOccurrence[] = structuredClone(DEMO_OPERATIONAL_OCCURRENCES)
export const EVENTOS_OPERACIONAIS: OperationalEvent[] = structuredClone(DEMO_OPERATIONAL_EVENTS)

export const ORDENS_EXECUCAO_SEMANA = [
  { dia: 'Seg', ordens: 118, meta: 130 },
  { dia: 'Ter', ordens: 134, meta: 130 },
  { dia: 'Qua', ordens: 129, meta: 130 },
  { dia: 'Qui', ordens: 151, meta: 130 },
  { dia: 'Sex', ordens: 162, meta: 130 },
  { dia: 'Sáb', ordens: 98, meta: 130 },
]

export const FLUXO_DIA = [
  { hora: '06h', recebido: 12, expedido: 4 },
  { hora: '08h', recebido: 34, expedido: 21 },
  { hora: '10h', recebido: 58, expedido: 47 },
  { hora: '12h', recebido: 41, expedido: 63 },
  { hora: '14h', recebido: 67, expedido: 88 },
  { hora: '16h', recebido: 52, expedido: 102 },
  { hora: '18h', recebido: 29, expedido: 74 },
]

export const OCUPACAO_ZONAS = [
  { zona: 'Picking A', ocupacao: 92 },
  { zona: 'Picking B', ocupacao: 78 },
  { zona: 'Pulmão', ocupacao: 84 },
  { zona: 'Refrigerados', ocupacao: 61 },
  { zona: 'Quarentena', ocupacao: 28 },
]

export const STATUS_PEDIDOS = [
  { name: 'Expedido', value: 248, cor: '#16a34a' },
  { name: 'Em packing', value: 42, cor: '#2563eb' },
  { name: 'Em separação', value: 67, cor: '#f97316' },
  { name: 'Aguardando', value: 31, cor: '#94a3b8' },
]

export const SKU_CONTROLE: SkuControle[] = [
  {
    id: 'sku-ctrl-1001',
    ownerId: 'own-nano',
    empresaId: 'emp-eletrolux',
    codigo: 'SKU-10241',
    descricao: 'Fone Bluetooth Pulse X',
    tipo: 'unidade',
    skuUnidadeConteudo: null,
    unidadesPorCaixa: null,
    comprimentoCm: 10,
    larguraCm: 5,
    alturaCm: 18,
    cubagemM3: 0.0009,
    criadoPor: 'Marina S.',
    criadoEm: '2026-06-18T09:12:00.000Z',
    atualizadoPor: 'Marina S.',
    atualizadoEm: '2026-06-18T09:12:00.000Z',
  },
  {
    id: 'sku-ctrl-1002',
    ownerId: 'own-nano',
    empresaId: 'emp-eletrolux',
    codigo: 'CX-10241-06',
    descricao: 'Caixa matriz · Fone Bluetooth Pulse X c/ 6 un',
    tipo: 'caixa-matriz',
    skuUnidadeConteudo: 'SKU-10241',
    unidadesPorCaixa: 6,
    comprimentoCm: 32,
    larguraCm: 21,
    alturaCm: 14,
    cubagemM3: 0.009408,
    criadoPor: 'Marina S.',
    criadoEm: '2026-06-18T09:20:00.000Z',
    atualizadoPor: 'Carlos M.',
    atualizadoEm: '2026-06-21T14:35:00.000Z',
  },
  {
    id: 'sku-ctrl-1003',
    ownerId: 'own-verde',
    empresaId: 'emp-carrefour',
    codigo: 'SKU-30011',
    descricao: 'Azeite Extra Virgem 500ml',
    tipo: 'unidade',
    skuUnidadeConteudo: null,
    unidadesPorCaixa: null,
    comprimentoCm: 7,
    larguraCm: 7,
    alturaCm: 25,
    cubagemM3: 0.001225,
    criadoPor: 'Ana P.',
    criadoEm: '2026-06-19T11:02:00.000Z',
    atualizadoPor: 'Ana P.',
    atualizadoEm: '2026-06-19T11:02:00.000Z',
  },
  {
    id: 'sku-ctrl-1004',
    ownerId: 'own-verde',
    empresaId: 'emp-carrefour',
    codigo: 'CX-30011-06',
    descricao: 'Caixa matriz · Azeite Extra Virgem 500ml c/ 6 un',
    tipo: 'caixa-matriz',
    skuUnidadeConteudo: 'SKU-30011',
    unidadesPorCaixa: 6,
    comprimentoCm: 23,
    larguraCm: 16,
    alturaCm: 27,
    cubagemM3: 0.009936,
    criadoPor: 'Ana P.',
    criadoEm: '2026-06-19T11:08:00.000Z',
    atualizadoPor: 'Patrícia L.',
    atualizadoEm: '2026-06-22T10:44:00.000Z',
  },
  {
    id: 'sku-ctrl-1005',
    ownerId: 'own-bella',
    empresaId: 'emp-magazine-luiza',
    codigo: 'SKU-20056',
    descricao: 'Base Líquida Tom 02',
    tipo: 'unidade',
    skuUnidadeConteudo: null,
    unidadesPorCaixa: null,
    comprimentoCm: 4,
    larguraCm: 4,
    alturaCm: 12,
    cubagemM3: 0.000192,
    criadoPor: 'João R.',
    criadoEm: '2026-06-20T08:50:00.000Z',
    atualizadoPor: 'João R.',
    atualizadoEm: '2026-06-20T08:50:00.000Z',
  },
  ...SKU_CONTROLE_COMPLEMENTAR,
]

export const SKU_CONTROLE_HISTORICO: SkuControleHistorico[] = [
  {
    id: 'sku-hist-1001',
    skuId: 'sku-ctrl-1002',
    skuCodigo: 'CX-10241-06',
    acao: 'edicao',
    usuario: 'Carlos M.',
    quando: '2026-06-21T14:35:00.000Z',
    resumo: 'Cubagem da caixa matriz revisada na homologação de recebimento.',
    alteracoes: [
      { campo: 'Comprimento', antes: '31 cm', depois: '32 cm' },
      { campo: 'Cubagem', antes: '0,009114 m³', depois: '0,009408 m³' },
    ],
  },
  {
    id: 'sku-hist-1002',
    skuId: 'sku-ctrl-1004',
    skuCodigo: 'CX-30011-06',
    acao: 'edicao',
    usuario: 'Patrícia L.',
    quando: '2026-06-22T10:44:00.000Z',
    resumo: 'Fator da caixa confirmado após conferência de amostra.',
    alteracoes: [
      { campo: 'Unidades por caixa', antes: '12', depois: '6' },
    ],
  },
  {
    id: 'sku-hist-1003',
    skuId: 'sku-ctrl-1005',
    skuCodigo: 'SKU-20056',
    acao: 'criacao',
    usuario: 'João R.',
    quando: '2026-06-20T08:50:00.000Z',
    resumo: 'SKU unidade cadastrado manualmente.',
    alteracoes: [
      { campo: 'Tipo', antes: '—', depois: 'Unidade' },
      { campo: 'Cubagem', antes: '—', depois: '0,000192 m³' },
    ],
  },
  ...SKU_CONTROLE_COMPLEMENTAR_HISTORICO,
]

export const RECEBIMENTOS: Recebimento[] = [
  {
    id: 'REC-2041',
    doca: 'Doca 03',
    fornecedor: 'Distribuidora Andrade',
    documento: 'NF-e 88.214',
    tipoDoc: 'NF-e',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-26',
    janela: '13:00-14:00',
    responsavel: 'Marina S.',
    placa: 'FJD-3A21',
    ordemDoca: 1,
    ordemExecucaoAtual: 4,
    eta: '13:10',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', esperado: 720, contado: null, conferido: false },
      { skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', esperado: 1200, contado: null, conferido: false },
      { skuCodigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', esperado: 2100, contado: null, conferido: false },
      { skuCodigo: 'SKU-10244', descricao: 'Power Bank 10000mAh', esperado: 480, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2042',
    doca: 'Doca 01',
    fornecedor: 'Verde Alimentos S/A',
    documento: 'ASN 5567',
    tipoDoc: 'ASN',
    ownerId: 'own-verde',
    vertente: '3pl',
    data: '2026-06-26',
    janela: '08:00-09:00',
    responsavel: 'Carlos M.',
    placa: 'BRA-8P44',
    ordemDoca: 2,
    ordemExecucaoAtual: 6,
    eta: '08:20',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', esperado: 240, contado: null, conferido: false, lote: 'L-2410', validade: '2026-10-12' },
      { skuCodigo: 'SKU-30012', descricao: 'Grão de Bico 1kg', esperado: 180, contado: null, conferido: false, lote: 'L-2255', validade: '2026-08-01' },
    ],
  },
  {
    id: 'REC-2043',
    doca: 'Doca 05',
    fornecedor: 'Forte Indústria Ltda',
    documento: 'NF-e 12.880',
    tipoDoc: 'NF-e',
    ownerId: 'own-forte',
    vertente: 'industria',
    data: '2026-06-17',
    janela: '10:00-11:00',
    responsavel: 'Patrícia L.',
    placa: 'JKM-9981',
    ordemDoca: 3,
    ordemExecucaoAtual: 1,
    eta: '10:00',
    status: 'agendado',
    itens: [
      { skuCodigo: 'MP-7781', descricao: 'Resina PET grau A', esperado: 50, contado: null, conferido: false, lote: 'MP-A-991', validade: '2027-01-01' },
      { skuCodigo: 'MP-7782', descricao: 'Pigmento Azul 04', esperado: 25, contado: null, conferido: false, lote: 'MP-B-552', validade: '2026-12-15' },
    ],
  },
  {
    id: 'REC-2040',
    doca: 'Doca 02',
    fornecedor: 'Bella Distribuição',
    documento: 'NF-e 44.120',
    tipoDoc: 'NF-e',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-14',
    janela: '07:30-08:30',
    responsavel: 'Ana P.',
    placa: 'BLR-2C10',
    ordemDoca: 1,
    ordemExecucaoAtual: 7,
    eta: '07:45',
    status: 'concluido',
    itens: [
      { skuCodigo: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', esperado: 300, contado: 300, conferido: true, lote: 'B-7781', validade: '2026-05-30' },
    ],
  },
  {
    id: 'REC-2044',
    doca: 'Doca 04',
    fornecedor: 'Nano Imports',
    documento: 'NF-e 88.318',
    tipoDoc: 'NF-e',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-18',
    janela: '11:00-12:00',
    responsavel: 'João R.',
    placa: 'NAN-7H32',
    ordemDoca: 4,
    ordemExecucaoAtual: 5,
    eta: '11:20',
    status: 'divergencia',
    itens: [
      { skuCodigo: 'SKU-10244', descricao: 'Power Bank 10000mAh', esperado: 100, contado: 96, conferido: true, ocorrencia: { tipo: 'falta', quantidadeReal: 96, observacao: 'Falta de 4 unidades no volume 03.', foto: true } },
      { skuCodigo: 'SKU-10245', descricao: 'Suporte Veicular Magnético', esperado: 180, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2045',
    doca: 'Doca 06',
    fornecedor: 'Bella Full Commerce',
    documento: 'ASN 5590',
    tipoDoc: 'ASN',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-26',
    janela: '10:00-11:00',
    responsavel: 'Marina S.',
    placa: 'BEL-5K02',
    ordemDoca: 5,
    ordemExecucaoAtual: 4,
    eta: '10:35',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-20056', descricao: 'Base Líquida Tom 02', esperado: 144, contado: null, conferido: false, lote: 'B-6610', validade: '2026-06-04' },
      { skuCodigo: 'SKU-20057', descricao: 'Batom Matte Rubi', esperado: 220, contado: null, conferido: false, lote: 'B-5540', validade: '2025-12-10' },
    ],
  },
  {
    id: 'REC-2046',
    doca: 'Doca 02',
    fornecedor: 'Global Parts Trading',
    documento: 'ASN 5604',
    tipoDoc: 'ASN',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-22',
    janela: '08:00-09:30',
    responsavel: 'Patrícia L.',
    placa: 'GPT-2M91',
    ordemDoca: 1,
    ordemExecucaoAtual: 1,
    eta: '08:20',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-10246', descricao: 'Hub USB-C 7 portas', esperado: 160, contado: null, conferido: false },
      { skuCodigo: 'SKU-10247', descricao: 'Mouse Vertical Pro', esperado: 90, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2050',
    doca: 'Doca 01',
    fornecedor: 'Grupo Aurora Supply',
    documento: 'NF-e 71.204',
    tipoDoc: 'NF-e',
    ownerId: 'own-forte',
    vertente: 'industria',
    data: '2026-06-22',
    janela: '07:00-08:00',
    responsavel: 'Carlos M.',
    placa: 'AUR-1B90',
    ordemDoca: 2,
    ordemExecucaoAtual: 1,
    eta: '07:10',
    status: 'agendado',
    itens: [
      { skuCodigo: 'MP-7790', descricao: 'Filme Stretch Industrial', esperado: 72, contado: null, conferido: false, lote: 'MP-D-100', validade: '2027-04-10' },
    ],
  },
  {
    id: 'REC-2051',
    doca: 'Doca 03',
    fornecedor: 'Bella Full Commerce',
    documento: 'ASN 5605',
    tipoDoc: 'ASN',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-22',
    janela: '08:30-09:30',
    responsavel: 'Marina S.',
    placa: 'BFC-8T41',
    ordemDoca: 3,
    ordemExecucaoAtual: 1,
    eta: '08:45',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-20059', descricao: 'Creme Hidratante 200ml', esperado: 260, contado: null, conferido: false, lote: 'B-6640', validade: '2026-08-10' },
      { skuCodigo: 'SKU-20060', descricao: 'Água Micelar 120ml', esperado: 180, contado: null, conferido: false, lote: 'B-6641', validade: '2026-08-15' },
    ],
  },
  {
    id: 'REC-2052',
    doca: 'Doca 04',
    fornecedor: 'Verde Alimentos S/A',
    documento: 'NF-e 33.920',
    tipoDoc: 'NF-e',
    ownerId: 'own-verde',
    vertente: '3pl',
    data: '2026-06-22',
    janela: '09:00-10:00',
    responsavel: 'Ana P.',
    placa: 'VDA-3P17',
    ordemDoca: 4,
    ordemExecucaoAtual: 1,
    eta: '09:30',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-30015', descricao: 'Granola Castanhas 500g', esperado: 320, contado: null, conferido: false, lote: 'L-2308', validade: '2026-12-05' },
    ],
  },
  {
    id: 'REC-2053',
    doca: 'Doca 05',
    fornecedor: 'Nano Imports',
    documento: 'ASN 5606',
    tipoDoc: 'ASN',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-22',
    janela: '10:00-11:00',
    responsavel: 'João R.',
    placa: 'NAN-2K44',
    ordemDoca: 5,
    ordemExecucaoAtual: 2,
    eta: '10:05',
    status: 'na-doca',
    itens: [
      { skuCodigo: 'SKU-10248', descricao: 'Teclado Mecânico Compacto', esperado: 84, contado: null, conferido: false },
      { skuCodigo: 'SKU-10249', descricao: 'Webcam Full HD', esperado: 96, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2054',
    doca: 'Doca 02',
    fornecedor: 'Forte Indústria Ltda',
    documento: 'NF-e 12.945',
    tipoDoc: 'NF-e',
    ownerId: 'own-forte',
    vertente: 'industria',
    data: '2026-06-22',
    janela: '10:30-11:30',
    responsavel: 'Patrícia L.',
    placa: 'FRI-2L70',
    ordemDoca: 6,
    ordemExecucaoAtual: 1,
    eta: '10:40',
    status: 'agendado',
    itens: [
      { skuCodigo: 'MP-7791', descricao: 'Tampa Injetada Natural', esperado: 40, contado: null, conferido: false, lote: 'MP-D-112', validade: '2027-01-25' },
    ],
  },
  {
    id: 'REC-2055',
    doca: 'Doca 06',
    fornecedor: 'Distribuidora Andrade',
    documento: 'NF-e 88.402',
    tipoDoc: 'NF-e',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-22',
    janela: '11:00-12:00',
    responsavel: undefined,
    placa: 'DAN-7R31',
    ordemDoca: 7,
    ordemExecucaoAtual: 1,
    eta: '11:15',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-10250', descricao: 'Cabo HDMI 2m', esperado: 420, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2056',
    doca: 'Doca 01',
    fornecedor: 'Cooperativa Vale Verde',
    documento: 'ASN 5607',
    tipoDoc: 'ASN',
    ownerId: 'own-verde',
    vertente: '3pl',
    data: '2026-06-22',
    janela: '12:00-13:00',
    responsavel: 'Carlos M.',
    placa: 'VVR-4D82',
    ordemDoca: 8,
    ordemExecucaoAtual: 7,
    eta: '12:00',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-30016', descricao: 'Mix de Castanhas 250g', esperado: 210, contado: null, conferido: false, lote: 'L-2315', validade: '2026-11-30' },
      { skuCodigo: 'SKU-30017', descricao: 'Chá Verde 30g', esperado: 180, contado: null, conferido: false, lote: 'L-2316', validade: '2027-01-10' },
    ],
  },
  {
    id: 'REC-2057',
    doca: 'Doca 03',
    fornecedor: 'Global Parts Trading',
    documento: 'ASN 5608',
    tipoDoc: 'ASN',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-22',
    janela: '13:00-14:00',
    responsavel: 'Marina S.',
    placa: 'GPT-6U29',
    ordemDoca: 9,
    ordemExecucaoAtual: 1,
    eta: '13:25',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-10251', descricao: 'Dock Station USB-C', esperado: 66, contado: null, conferido: false },
    ],
  },
  {
    id: 'REC-2058',
    doca: 'Doca 04',
    fornecedor: 'Bella Distribuição',
    documento: 'NF-e 44.188',
    tipoDoc: 'NF-e',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-22',
    janela: '14:00-15:00',
    responsavel: 'Ana P.',
    placa: 'BLR-6J20',
    ordemDoca: 10,
    ordemExecucaoAtual: 1,
    eta: '14:10',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-20061', descricao: 'Protetor Solar FPS 50', esperado: 300, contado: null, conferido: false, lote: 'B-6649', validade: '2026-10-20' },
    ],
  },
  {
    id: 'REC-2047',
    doca: 'Doca 05',
    fornecedor: 'Cooperativa Vale Verde',
    documento: 'NF-e 33.902',
    tipoDoc: 'NF-e',
    ownerId: 'own-verde',
    vertente: '3pl',
    data: '2026-06-23',
    janela: '10:00-11:30',
    responsavel: 'Carlos M.',
    placa: 'VVR-9C18',
    ordemDoca: 2,
    ordemExecucaoAtual: 1,
    eta: '10:15',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-30013', descricao: 'Molho de Tomate Orgânico 340g', esperado: 360, contado: null, conferido: false, lote: 'L-2288', validade: '2026-11-20' },
      { skuCodigo: 'SKU-30014', descricao: 'Farinha Integral 1kg', esperado: 240, contado: null, conferido: false, lote: 'L-2301', validade: '2026-09-18' },
    ],
  },
  {
    id: 'REC-2048',
    doca: 'Doca 03',
    fornecedor: 'Bella Full Commerce',
    documento: 'ASN 5612',
    tipoDoc: 'ASN',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-24',
    janela: '13:00-14:00',
    responsavel: 'Marina S.',
    placa: 'BFC-4D22',
    ordemDoca: 3,
    ordemExecucaoAtual: 1,
    eta: '13:05',
    status: 'agendado',
    itens: [
      { skuCodigo: 'SKU-20058', descricao: 'Máscara Facial Hidratação', esperado: 420, contado: null, conferido: false, lote: 'B-6622', validade: '2026-07-04' },
    ],
  },
  {
    id: 'REC-2049',
    doca: 'Doca 06',
    fornecedor: 'Forte Indústria Ltda',
    documento: 'NF-e 12.941',
    tipoDoc: 'NF-e',
    ownerId: 'own-forte',
    vertente: 'industria',
    data: '2026-06-26',
    janela: '15:00-16:30',
    responsavel: 'Patrícia L.',
    placa: 'FRI-7K80',
    ordemDoca: 4,
    ordemExecucaoAtual: 4,
    eta: '15:20',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'MP-7784', descricao: 'Aditivo antiestático', esperado: 32, contado: null, conferido: false, lote: 'MP-C-118', validade: '2027-02-10' },
      { skuCodigo: 'MP-7785', descricao: 'Masterbatch Preto', esperado: 44, contado: null, conferido: false, lote: 'MP-C-221', validade: '2027-03-14' },
    ],
  },
  {
    id: 'REC-2059',
    doca: 'Doca 03',
    fornecedor: 'Global Parts Trading',
    documento: 'ASN 5618',
    tipoDoc: 'ASN',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-26',
    janela: '09:30-10:30',
    responsavel: 'Marina S.',
    placa: 'GPT-4N18',
    ordemDoca: 6,
    ordemExecucaoAtual: 6,
    eta: '09:45',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', esperado: 180, contado: 180, conferido: true },
      { skuCodigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', esperado: 300, contado: 300, conferido: true },
      { skuCodigo: 'SKU-10244', descricao: 'Power Bank 10000mAh', esperado: 72, contado: 72, conferido: true },
    ],
  },
  {
    id: 'REC-2070',
    doca: 'Doca 07',
    fornecedor: 'Carga Teste Montagem',
    documento: 'ASN 5700',
    tipoDoc: 'ASN',
    ownerId: 'own-nano',
    vertente: 'ecommerce',
    data: '2026-06-30',
    janela: '10:30-11:30',
    responsavel: 'Marina S.',
    placa: 'TST-2P70',
    ordemDoca: 9,
    ordemExecucaoAtual: 6,
    eta: '10:35',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', esperado: 5750, contado: 5750, conferido: true },
      { skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', esperado: 1400, contado: 1400, conferido: true },
    ],
  },
  {
    id: 'REC-2060',
    doca: 'Doca 05',
    fornecedor: 'Bella Full Commerce',
    documento: 'NF-e 44.203',
    tipoDoc: 'NF-e',
    ownerId: 'own-bella',
    vertente: '3pl',
    data: '2026-06-26',
    janela: '11:30-12:30',
    responsavel: 'Ana P.',
    placa: 'BFC-7A44',
    ordemDoca: 7,
    ordemExecucaoAtual: 6,
    eta: '11:50',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'SKU-20056', descricao: 'Base Líquida Tom 02', esperado: 120, contado: 120, conferido: true, lote: 'B-6682', validade: '2026-09-30' },
      { skuCodigo: 'SKU-20058', descricao: 'Máscara Facial Hidratação', esperado: 180, contado: 180, conferido: true, lote: 'B-6683', validade: '2026-10-12' },
      { skuCodigo: 'SKU-20060', descricao: 'Água Micelar 120ml', esperado: 96, contado: 96, conferido: true, lote: 'B-6684', validade: '2026-11-05' },
    ],
  },
  {
    id: 'REC-2061',
    doca: 'Doca 02',
    fornecedor: 'Forte Indústria Ltda',
    documento: 'NF-e 12.962',
    tipoDoc: 'NF-e',
    ownerId: 'own-forte',
    vertente: 'industria',
    data: '2026-06-26',
    janela: '14:00-15:00',
    responsavel: 'Patrícia L.',
    placa: 'FRI-4P62',
    ordemDoca: 8,
    ordemExecucaoAtual: 6,
    eta: '14:15',
    status: 'em-conferencia',
    itens: [
      { skuCodigo: 'MP-7784', descricao: 'Aditivo antiestático', esperado: 64, contado: 64, conferido: true, lote: 'MP-C-140', validade: '2027-04-10' },
      { skuCodigo: 'MP-7785', descricao: 'Masterbatch Preto', esperado: 55, contado: 55, conferido: true, lote: 'MP-C-236', validade: '2027-04-22' },
      { skuCodigo: 'MP-7790', descricao: 'Filme Stretch Industrial', esperado: 36, contado: 36, conferido: true, lote: 'MP-D-130', validade: '2027-06-12' },
    ],
  },
]

export const VIAGENS_ETIQUETAGEM: ViagemEtiquetagem[] = [
  {
    id: 'VIA-IN-7801',
    recebimentoId: 'REC-2042',
    ordemServicoId: 'OS-9102',
    ordemExecucaoAtual: 6,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260655670001',
    nf: 'NF-e 33.891',
    origemSigla: 'MG',
    destinoSigla: 'SP',
    embarcador: 'Verde Alimentos S/A',
    destinatario: 'Verde Alimentos · CD Cajamar',
    endereco: 'Av. Dr. Antonio Joao Abdalla, 260 - Cajamar/SP',
    itens: [
      {
        skuCodigo: 'SKU-30011',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 6,
        pesoUnitarioKg: 0.62,
        volumesDocumento: 40,
      },
      {
        skuCodigo: 'SKU-30012',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 12,
        pesoUnitarioKg: 1.04,
        volumesDocumento: 15,
      },
    ],
  },
  {
    id: 'VIA-IN-7802',
    recebimentoId: 'REC-2045',
    ordemServicoId: 'OS-9105',
    ordemExecucaoAtual: 4,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260655900002',
    nf: 'NF-e 44.171',
    origemSigla: 'PR',
    destinoSigla: 'SP',
    embarcador: 'Bella Full Commerce',
    destinatario: 'Bella Cosméticos · Reserva e-commerce',
    endereco: 'Rua das Flores, 1180 - Galpao 2 - Cajamar/SP',
    itens: [
      {
        skuCodigo: 'SKU-20056',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 6,
        pesoUnitarioKg: 0.18,
        volumesDocumento: 24,
      },
      {
        skuCodigo: 'SKU-20057',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 1,
        pesoUnitarioKg: 0.04,
        volumesDocumento: 220,
      },
    ],
  },
  {
    id: 'VIA-IN-7803',
    recebimentoId: 'REC-2044',
    ordemServicoId: 'OS-9104',
    ordemExecucaoAtual: 4,
    documentoStatus: 'bloqueado',
    cte: 'CT-e 35260688318003',
    nf: 'NF-e 88.318',
    origemSigla: 'SC',
    destinoSigla: 'SP',
    embarcador: 'Nano Imports',
    destinatario: 'NanoTech Eletrônicos · Quarentena inbound',
    endereco: 'Av. Tambore, 1512 - Barueri/SP',
    itens: [
      {
        skuCodigo: 'SKU-10244',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 4,
        pesoUnitarioKg: 0.25,
        volumesDocumento: 25,
      },
      {
        skuCodigo: 'SKU-10245',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 1,
        pesoUnitarioKg: 0.08,
        volumesDocumento: 180,
      },
    ],
  },
  {
    id: 'VIA-IN-7804',
    recebimentoId: 'REC-2041',
    ordemServicoId: 'OS-9101',
    ordemExecucaoAtual: 4,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260688214004',
    nf: 'NF-e 88.214',
    origemSigla: 'SC',
    destinoSigla: 'SP',
    embarcador: 'Distribuidora Andrade',
    destinatario: 'NanoTech Eletrônicos · Recebimento Cajamar',
    endereco: 'Av. Tambore, 1512 - Barueri/SP',
    itens: [
      {
        skuCodigo: 'SKU-10241',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 1,
        pesoUnitarioKg: 0.16,
        volumesDocumento: 720,
      },
      {
        skuCodigo: 'SKU-10242',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 10,
        pesoUnitarioKg: 0.11,
        volumesDocumento: 120,
      },
      {
        skuCodigo: 'SKU-10243',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 25,
        pesoUnitarioKg: 0.04,
        volumesDocumento: 84,
      },
      {
        skuCodigo: 'SKU-10244',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 4,
        pesoUnitarioKg: 0.25,
        volumesDocumento: 120,
      },
    ],
  },
  {
    id: 'VIA-IN-7805',
    recebimentoId: 'REC-2049',
    ordemServicoId: 'OS-9107',
    ordemExecucaoAtual: 4,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260612941005',
    nf: 'NF-e 12.941',
    origemSigla: 'PR',
    destinoSigla: 'SP',
    embarcador: 'Forte Indústria Ltda',
    destinatario: 'Forte Indústria · Qualidade inbound',
    endereco: 'Av. Dr. Antonio Joao Abdalla, 260 - Cajamar/SP',
    itens: [
      {
        skuCodigo: 'MP-7784',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 8,
        pesoUnitarioKg: 1.2,
        volumesDocumento: 4,
      },
      {
        skuCodigo: 'MP-7785',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 11,
        pesoUnitarioKg: 1.4,
        volumesDocumento: 4,
      },
    ],
  },
  {
    id: 'VIA-IN-7806',
    recebimentoId: 'REC-2059',
    ordemServicoId: 'OS-9110',
    ordemExecucaoAtual: 6,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260656180006',
    nf: 'NF-e 88.436',
    origemSigla: 'SC',
    destinoSigla: 'SP',
    embarcador: 'Global Parts Trading',
    destinatario: 'NanoTech Eletrônicos · Montagem inbound',
    endereco: 'Av. Tambore, 1512 - Barueri/SP',
    itens: [
      {
        skuCodigo: 'SKU-10242',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 10,
        pesoUnitarioKg: 0.11,
        volumesDocumento: 18,
      },
      {
        skuCodigo: 'SKU-10243',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 25,
        pesoUnitarioKg: 0.04,
        volumesDocumento: 12,
      },
      {
        skuCodigo: 'SKU-10244',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 4,
        pesoUnitarioKg: 0.25,
        volumesDocumento: 18,
      },
    ],
  },
  {
    id: 'VIA-IN-7810',
    recebimentoId: 'REC-2070',
    ordemServicoId: 'OS-9113',
    ordemExecucaoAtual: 6,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260657000010',
    nf: 'ASN 5700',
    origemSigla: 'SC',
    destinoSigla: 'SP',
    embarcador: 'Carga Teste Montagem',
    destinatario: 'NanoTech Eletronicos - Montagem 2 pallets',
    endereco: 'Av. Tambore, 1512 - Barueri/SP',
    itens: [
      {
        skuCodigo: 'SKU-10243',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 25,
        pesoUnitarioKg: 0.04,
        volumesDocumento: 230,
      },
      {
        skuCodigo: 'SKU-10242',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 10,
        pesoUnitarioKg: 0.11,
        volumesDocumento: 140,
      },
    ],
  },
  {
    id: 'VIA-IN-7807',
    recebimentoId: 'REC-2060',
    ordemServicoId: 'OS-9111',
    ordemExecucaoAtual: 6,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260644203007',
    nf: 'NF-e 44.203',
    origemSigla: 'PR',
    destinoSigla: 'SP',
    embarcador: 'Bella Full Commerce',
    destinatario: 'Bella Cosméticos · Montagem inbound',
    endereco: 'Rua das Flores, 1180 - Galpao 2 - Cajamar/SP',
    itens: [
      {
        skuCodigo: 'SKU-20056',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 6,
        pesoUnitarioKg: 0.18,
        volumesDocumento: 20,
      },
      {
        skuCodigo: 'SKU-20058',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 12,
        pesoUnitarioKg: 0.05,
        volumesDocumento: 15,
      },
      {
        skuCodigo: 'SKU-20060',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 12,
        pesoUnitarioKg: 0.14,
        volumesDocumento: 8,
      },
    ],
  },
  {
    id: 'VIA-IN-7808',
    recebimentoId: 'REC-2061',
    ordemServicoId: 'OS-9112',
    ordemExecucaoAtual: 6,
    documentoStatus: 'aprovado',
    cte: 'CT-e 35260612962008',
    nf: 'NF-e 12.962',
    origemSigla: 'PR',
    destinoSigla: 'SP',
    embarcador: 'Forte Indústria Ltda',
    destinatario: 'Forte Indústria · Montagem inbound',
    endereco: 'Av. Dr. Antonio Joao Abdalla, 260 - Cajamar/SP',
    itens: [
      {
        skuCodigo: 'MP-7784',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 8,
        pesoUnitarioKg: 1.2,
        volumesDocumento: 8,
      },
      {
        skuCodigo: 'MP-7785',
        tipoEmbalagem: 'caixa-matriz',
        unidadesPorVolume: 11,
        pesoUnitarioKg: 1.4,
        volumesDocumento: 5,
      },
      {
        skuCodigo: 'MP-7790',
        tipoEmbalagem: 'unidade',
        unidadesPorVolume: 6,
        pesoUnitarioKg: 2.1,
        volumesDocumento: 6,
      },
    ],
  },
]

export const ESTOQUE: PosicaoEstoque[] = [
  { id: 'e1', skuCodigo: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', endereco: 'A-12-03-2', lote: null, validade: null, ownerId: 'own-nano', curva: 'A', quantidade: 84, status: 'disponivel' },
  { id: 'e2', skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', endereco: 'A-12-04-1', lote: null, validade: null, ownerId: 'own-nano', curva: 'A', quantidade: 156, status: 'disponivel' },
  { id: 'e3', skuCodigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', endereco: 'A-13-01-1', lote: null, validade: null, ownerId: 'own-nano', curva: 'A', quantidade: 12, status: 'disponivel' },
  { id: 'e4', skuCodigo: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', endereco: 'B-04-12-3', lote: 'B-7781', validade: '2026-05-30', ownerId: 'own-bella', curva: 'B', quantidade: 300, status: 'disponivel' },
  { id: 'e5', skuCodigo: 'SKU-20056', descricao: 'Base Líquida Tom 02', endereco: 'B-05-02-2', lote: 'B-6610', validade: '2026-06-04', ownerId: 'own-bella', curva: 'B', quantidade: 45, status: 'quarentena' },
  { id: 'e6', skuCodigo: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', endereco: 'C-08-01-1', lote: 'L-2410', validade: '2026-10-12', ownerId: 'own-verde', curva: 'B', quantidade: 240, status: 'disponivel' },
  { id: 'e7', skuCodigo: 'SKU-30012', descricao: 'Grão de Bico 1kg', endereco: 'C-08-03-1', lote: 'L-2255', validade: '2026-08-01', ownerId: 'own-verde', curva: 'C', quantidade: 180, status: 'disponivel' },
  { id: 'e8', skuCodigo: 'MP-7781', descricao: 'Resina PET grau A', endereco: 'D-01-01-1', lote: 'MP-A-991', validade: '2027-01-01', ownerId: 'own-forte', curva: 'C', quantidade: 50, status: 'qualidade' },
  { id: 'e9', skuCodigo: 'SKU-10244', descricao: 'Power Bank 10000mAh', endereco: 'A-14-02-2', lote: null, validade: null, ownerId: 'own-nano', curva: 'A', quantidade: 8, status: 'reservado' },
  { id: 'e10', skuCodigo: 'SKU-20057', descricao: 'Batom Matte Rubi', endereco: 'B-06-01-1', lote: 'B-5540', validade: '2025-12-10', ownerId: 'own-bella', curva: 'C', quantidade: 22, status: 'avaria' },
]

export const TAREFAS: Tarefa[] = [
  { id: 'OS-9101', tipo: 'recebimento', prioridade: 'alta', operador: 'Marina S.', status: 'fazendo', origem: 'Doca 03', destino: 'Área de etiquetagem', sku: 'NF-e 88.214', descricao: 'Gerar etiquetas de volume para REC-2041', quantidade: 4, sla: '13:35', etapa: 'Geração de etiquetas', referenciaTipo: 'recebimento', referenciaId: 'REC-2041' },
  { id: 'OS-9102', tipo: 'recebimento', prioridade: 'media', operador: 'Carlos M.', status: 'fazendo', origem: 'Doca 01', destino: 'Área de etiquetagem', sku: 'ASN 5567', descricao: 'Gerar etiquetas de volume para REC-2042', quantidade: 2, sla: '08:45', etapa: 'Geração de etiquetas', referenciaTipo: 'recebimento', referenciaId: 'REC-2042' },
  { id: 'OS-9103', tipo: 'divergencia', prioridade: 'alta', operador: 'Líder turno A', status: 'problema', origem: 'Doca 02', destino: 'Tratativa fiscal', sku: 'SKU-20055', descricao: 'Validar divergência fiscal antes de liberar putaway', quantidade: 1, sla: '09:30', etapa: 'Divergência', referenciaTipo: 'recebimento', referenciaId: 'REC-2040', problema: 'Quantidade física precisa de validação do supervisor.' },
  { id: 'OS-9104', tipo: 'recebimento', prioridade: 'alta', operador: 'João R.', status: 'fazendo', origem: 'Doca 04', destino: 'Área de conferência', sku: 'NF-e 88.318', descricao: 'Recontar volumes com falta no recebimento REC-2044', quantidade: 2, sla: '11:40', etapa: 'Tratativa de falta', referenciaTipo: 'recebimento', referenciaId: 'REC-2044' },
  { id: 'OS-9105', tipo: 'recebimento', prioridade: 'media', operador: 'Marina S.', status: 'fazendo', origem: 'Doca 06', destino: 'Área de etiquetagem', sku: 'ASN 5590', descricao: 'Gerar etiquetas de volume para REC-2045', quantidade: 2, sla: '10:50', etapa: 'Geração de etiquetas', referenciaTipo: 'recebimento', referenciaId: 'REC-2045' },
  { id: 'OS-9106', tipo: 'divergencia', prioridade: 'media', operador: 'Patrícia L.', status: 'a-fazer', origem: 'Doca 04', destino: 'Compras/Fiscal', sku: 'SKU-10244', descricao: 'Validar aceite parcial de Power Bank no REC-2044', quantidade: 4, sla: '12:10', etapa: 'Decisão de divergência', referenciaTipo: 'recebimento', referenciaId: 'REC-2044' },
  { id: 'OS-9107', tipo: 'recebimento', prioridade: 'alta', operador: 'Patrícia L.', status: 'fazendo', origem: 'Doca 06', destino: 'Área de etiquetagem', sku: 'NF-e 12.941', descricao: 'Gerar etiquetas de volume para REC-2049', quantidade: 2, sla: '15:45', etapa: 'Geração de etiquetas', referenciaTipo: 'recebimento', referenciaId: 'REC-2049' },
  { id: 'OS-9110', tipo: 'recebimento', prioridade: 'alta', operador: 'Marina S.', status: 'fazendo', origem: 'Área de etiquetagem', destino: 'Área de montagem de pallets', sku: 'ASN 5618', descricao: 'Montar pallets do recebimento REC-2059', quantidade: 48, sla: '10:25', etapa: 'Montagem de pallets', referenciaTipo: 'recebimento', referenciaId: 'REC-2059' },
  { id: 'OS-9111', tipo: 'recebimento', prioridade: 'media', operador: 'Ana P.', status: 'a-fazer', origem: 'Área de etiquetagem', destino: 'Área de montagem de pallets', sku: 'NF-e 44.203', descricao: 'Montar pallets do recebimento REC-2060', quantidade: 43, sla: '12:20', etapa: 'Montagem de pallets', referenciaTipo: 'recebimento', referenciaId: 'REC-2060' },
  { id: 'OS-9112', tipo: 'recebimento', prioridade: 'media', operador: 'Patrícia L.', status: 'fazendo', origem: 'Área de etiquetagem', destino: 'Área de montagem de pallets', sku: 'NF-e 12.962', descricao: 'Montar pallets do recebimento REC-2061', quantidade: 19, sla: '14:50', etapa: 'Montagem de pallets', referenciaTipo: 'recebimento', referenciaId: 'REC-2061' },
  { id: 'OS-9201', tipo: 'putaway', prioridade: 'alta', operador: null, status: 'a-fazer', origem: 'STG-REC-03', destino: ADMIN_BUSINESS_PUTAWAY.nanoPrincipal, sku: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', quantidade: 120, sla: '08:55', etapa: 'Endereçamento sugerido', referenciaTipo: 'recebimento', referenciaId: 'REC-2041' },
  { id: 'OS-9202', tipo: 'putaway', prioridade: 'media', operador: null, status: 'a-fazer', origem: 'STG-REC-03', destino: ADMIN_BUSINESS_PUTAWAY.nanoSecundario, sku: 'SKU-10242', descricao: 'Carregador Turbo 30W', quantidade: 200, sla: '09:10', etapa: 'Endereçamento sugerido', referenciaTipo: 'recebimento', referenciaId: 'REC-2041' },
  { id: 'OS-9203', tipo: 'putaway', prioridade: 'alta', operador: 'Carlos M.', status: 'fazendo', origem: 'PISO-REC-01', destino: ADMIN_BUSINESS_PUTAWAY.verdePrincipal, sku: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', quantidade: 240, sla: '09:45', etapa: 'FEFO refrigerado', referenciaTipo: 'recebimento', referenciaId: 'REC-2042' },
  { id: 'OS-9204', tipo: 'putaway', prioridade: 'media', operador: null, status: 'a-fazer', origem: 'PISO-REC-01', destino: ADMIN_BUSINESS_PUTAWAY.verdeSecundario, sku: 'SKU-30012', descricao: 'Grão de Bico 1kg', quantidade: 180, sla: '10:05', etapa: 'Endereçamento sugerido', referenciaTipo: 'recebimento', referenciaId: 'REC-2042' },
  { id: 'OS-9205', tipo: 'putaway', prioridade: 'baixa', operador: 'Ana P.', status: 'feito', origem: 'STG-REC-02', destino: ADMIN_BUSINESS_PUTAWAY.bellaPrincipal, sku: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', quantidade: 300, sla: '08:30', etapa: 'Guardado', referenciaTipo: 'recebimento', referenciaId: 'REC-2040' },
  { id: 'OS-9206', tipo: 'putaway', prioridade: 'alta', operador: null, status: 'problema', origem: 'PISO-REC-04', destino: ADMIN_BUSINESS_PUTAWAY.excecaoQualidade, sku: 'SKU-10244', descricao: 'Power Bank 10000mAh', quantidade: 96, sla: '12:20', etapa: 'Quarentena por divergência', referenciaTipo: 'recebimento', referenciaId: 'REC-2044', problema: 'Aguardar decisão fiscal antes de liberar para estoque disponível.' },
  { id: 'OS-9207', tipo: 'putaway', prioridade: 'media', operador: null, status: 'a-fazer', origem: 'STG-REC-06', destino: ADMIN_BUSINESS_PUTAWAY.bellaSecundario, sku: 'SKU-20056', descricao: 'Base Líquida Tom 02', quantidade: 144, sla: '13:40', etapa: 'Endereçamento recorrente', referenciaTipo: 'recebimento', referenciaId: 'REC-2045' },
  { id: 'OS-9301', tipo: 'picking', prioridade: 'alta', operador: 'Carlos M.', status: 'fazendo', origem: 'A-12-03-2', destino: 'PACK-01', sku: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', quantidade: 2, sla: '08:40', ondaId: 'OND-501', etapa: 'Separação', referenciaTipo: 'onda', referenciaId: 'OND-501' },
  { id: 'OS-9302', tipo: 'picking', prioridade: 'alta', operador: 'Carlos M.', status: 'a-fazer', origem: 'A-12-04-1', destino: 'PACK-01', sku: 'SKU-10242', descricao: 'Carregador Turbo 30W', quantidade: 1, sla: '08:40', ondaId: 'OND-501', etapa: 'Separação', referenciaTipo: 'onda', referenciaId: 'OND-501' },
  { id: 'OS-9401', tipo: 'reabastecimento', prioridade: 'alta', operador: null, status: 'a-fazer', origem: 'PUL-A-22', destino: 'A-13-01-1', sku: 'SKU-10243', descricao: 'Cabo USB-C 2m', quantidade: 144, sla: '09:00', etapa: 'Pulmão para picking', referenciaTipo: 'endereco', referenciaId: 'A-13-01-1' },
  { id: 'OS-9501', tipo: 'contagem', prioridade: 'baixa', operador: null, status: 'a-fazer', origem: 'A-12-03-2', destino: '—', sku: 'SKU-10241', descricao: 'Contagem cega de Fone Bluetooth Pulse X', quantidade: 0, sla: '12:00', etapa: 'Contagem cega', referenciaTipo: 'contagem', referenciaId: 'CT-01' },
  { id: 'OS-9502', tipo: 'recontagem', prioridade: 'media', operador: 'Patrícia L.', status: 'problema', origem: 'B-04-12-3', destino: 'Aprovação', sku: 'SKU-20055', descricao: 'Recontagem por divergência acima da tolerância', quantidade: 0, sla: '11:20', etapa: 'Recontagem', referenciaTipo: 'contagem', referenciaId: 'CT-03', problema: 'Primeira contagem divergiu do saldo sistêmico.' },
  { id: 'OS-9601', tipo: 'packing', prioridade: 'alta', operador: 'Ana P.', status: 'fazendo', origem: 'PACK-01', destino: 'ROM-3301', sku: 'PED-77120', descricao: 'Conferência de saída, cubagem e etiqueta', quantidade: 1, sla: '10:00', etapa: 'Packing', referenciaTipo: 'pedido', referenciaId: 'PED-77120' },
  { id: 'OS-9602', tipo: 'carregamento', prioridade: 'alta', operador: null, status: 'a-fazer', origem: 'ROM-3301', destino: 'Van — PLT-2D45', sku: 'ROM-3301', descricao: 'Bipar volumes no veículo e liberar despacho', quantidade: 2, sla: '10:30', etapa: 'Conferência de carregamento', referenciaTipo: 'romaneio', referenciaId: 'ROM-3301' },
  { id: 'OS-9701', tipo: 'cross-docking', prioridade: 'alta', operador: null, status: 'a-fazer', origem: 'STG-REC-01', destino: ADMIN_BUSINESS_DOCAS.mista04, sku: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', quantidade: 48, sla: '08:50', etapa: 'Triagem direta', referenciaTipo: 'recebimento', referenciaId: 'REC-2042' },
]

export const ONDAS: Onda[] = [
  { id: 'OND-501', estrategia: 'cluster', pedidos: 24, linhas: 86, itens: 142, status: 'em-separacao', corte: '08:00', progresso: 62, coletaId: 'COL-4421', rota: 'SP-Capital', transportadora: 'Correios', doca: 'DOCA-03' },
  { id: 'OND-502', estrategia: 'batch', pedidos: 58, linhas: 58, itens: 410, status: 'liberada', corte: '10:00', progresso: 0, coletaId: 'COL-4422', rota: 'Interior-SP', transportadora: 'Jamef', doca: 'DOCA-04' },
  { id: 'OND-503', estrategia: 'wave', pedidos: 31, linhas: 120, itens: 240, status: 'planejada', corte: '14:00', progresso: 0, coletaId: 'COL-4423', rota: 'RJ-Capital', transportadora: 'Rápido Brasil', doca: 'DOCA-05' },
  { id: 'OND-500', estrategia: 'zona', pedidos: 40, linhas: 156, itens: 320, status: 'concluida', corte: '06:00', progresso: 100, coletaId: 'COL-4419', rota: 'SP-Capital', transportadora: 'Correios', doca: 'DOCA-03' },
]

export const PEDIDOS: Pedido[] = [
  {
    id: 'PED-77120', cliente: 'João Pereira', ownerId: 'own-nano', transportadora: 'Correios SEDEX', rota: 'SP-Capital', status: 'em-packing', peso: 1.2, volumes: 1, prazo: 'Hoje 18h', coletaId: 'COL-4421', ondaId: 'OND-501', reservaStatus: 'reservado',
    itens: [
      { skuCodigo: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', quantidade: 1, conferido: 0 },
      { skuCodigo: 'SKU-10243', descricao: 'Cabo USB-C 2m', quantidade: 2, conferido: 0 },
    ],
  },
  {
    id: 'PED-77121', cliente: 'Maria Silva', ownerId: 'own-bella', transportadora: 'Loggi', rota: 'SP-Capital', status: 'em-separacao', peso: 0.4, volumes: 1, prazo: 'Hoje 18h', coletaId: 'COL-4421', ondaId: 'OND-501', reservaStatus: 'reservado',
    itens: [{ skuCodigo: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', quantidade: 2, conferido: 0 }],
  },
  {
    id: 'PED-77122', cliente: 'Mercado Bom Preço', ownerId: 'own-verde', transportadora: 'Jamef', rota: 'Interior-SP', status: 'aguardando', peso: 18.5, volumes: 3, prazo: 'Amanhã 12h', coletaId: 'COL-4422', ondaId: 'OND-502', reservaStatus: 'parcial',
    itens: [
      { skuCodigo: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', quantidade: 24, conferido: 0 },
      { skuCodigo: 'SKU-30012', descricao: 'Grão de Bico 1kg', quantidade: 12, conferido: 0 },
    ],
  },
  {
    id: 'PED-77119', cliente: 'Ana Costa', ownerId: 'own-nano', transportadora: 'Correios PAC', rota: 'SP-Capital', status: 'expedido', peso: 0.3, volumes: 1, prazo: 'Hoje 18h', coletaId: 'COL-4421', ondaId: 'OND-500', reservaStatus: 'reservado',
    itens: [{ skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', quantidade: 1, conferido: 1 }],
  },
]

export const CONTAGENS: ContagemItem[] = [
  { id: 'CT-01', endereco: 'A-12-03-2', skuCodigo: 'SKU-10241', descricao: 'Fone Bluetooth Pulse X', sistemico: 84, contado: null, recontagem: null, status: 'pendente', ownerId: 'own-nano' },
  { id: 'CT-02', endereco: 'A-12-04-1', skuCodigo: 'SKU-10242', descricao: 'Carregador Turbo 30W', sistemico: 156, contado: null, recontagem: null, status: 'pendente', ownerId: 'own-nano' },
  { id: 'CT-03', endereco: 'B-04-12-3', skuCodigo: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', sistemico: 300, contado: null, recontagem: null, status: 'pendente', ownerId: 'own-bella' },
  { id: 'CT-04', endereco: 'C-08-01-1', skuCodigo: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', sistemico: 240, contado: null, recontagem: null, status: 'pendente', ownerId: 'own-verde' },
]

export const FATURAS: FaturaServico[] = [
  { ownerId: 'own-nano', armazenagem: 12400, movimentacaoEntrada: 3800, movimentacaoSaida: 9600, pickingLinhas: 7250, vas: 1500, paletesDia: 310, total: 34550 },
  { ownerId: 'own-bella', armazenagem: 8600, movimentacaoEntrada: 2100, movimentacaoSaida: 6400, pickingLinhas: 4800, vas: 3200, paletesDia: 180, total: 25100 },
  { ownerId: 'own-verde', armazenagem: 15200, movimentacaoEntrada: 4500, movimentacaoSaida: 7100, pickingLinhas: 3900, vas: 800, paletesDia: 420, total: 31500 },
  { ownerId: 'own-forte', armazenagem: 9800, movimentacaoEntrada: 5200, movimentacaoSaida: 4300, pickingLinhas: 2100, vas: 0, paletesDia: 260, total: 21400 },
]

export const INTEGRACOES: Integracao[] = [
  { id: 'int-erp', nome: 'SAP ERP', tipo: 'ERP', status: 'conectado', ultimaSync: 'há 2 min', registros: 18420 },
  { id: 'int-tms', nome: 'TMS Frete Fácil', tipo: 'TMS', status: 'conectado', ultimaSync: 'há 5 min', registros: 3120 },
  { id: 'int-ml', nome: 'Mercado Livre', tipo: 'Marketplace', status: 'sincronizando', ultimaSync: 'agora', registros: 8870 },
  { id: 'int-shp', nome: 'Shopee', tipo: 'Marketplace', status: 'conectado', ultimaSync: 'há 1 min', registros: 6210 },
  { id: 'int-edi', nome: 'EDI Carrefour', tipo: 'EDI', status: 'erro', ultimaSync: 'há 48 min', registros: 940 },
  { id: 'int-cor', nome: 'Correios', tipo: 'Transportadora', status: 'conectado', ultimaSync: 'há 3 min', registros: 5400 },
]

export const ROMANEIOS: Romaneio[] = [
  {
    id: 'ROM-3301', transportadora: 'Correios', rota: 'SP-Capital', veiculo: 'Van — PLT-2D45', status: 'em-carregamento', coletaId: 'COL-4421', doca: 'DOCA-03', janela: '10:00-10:30', placa: 'PLT-2D45',
    volumes: [
      { pedido: 'PED-77119', volumes: 1, peso: 0.3, carregado: true, codigoVolume: 'VOL-77119-1', lacre: 'LCR-8841', staging: 'STG-EXP-03' },
      { pedido: 'PED-77120', volumes: 1, peso: 1.2, carregado: false, codigoVolume: 'VOL-77120-1', lacre: 'LCR-8842', staging: 'STG-EXP-03' },
    ],
  },
  {
    id: 'ROM-3302', transportadora: 'Jamef', rota: 'Interior-SP', veiculo: 'Truck — JKM-9981', status: 'montando', coletaId: 'COL-4422', doca: 'DOCA-04', janela: '12:00-12:40', placa: 'JKM-9981',
    volumes: [{ pedido: 'PED-77122', volumes: 3, peso: 18.5, carregado: false, codigoVolume: 'VOL-77122-1/3', lacre: 'Aguardando', staging: 'STG-EXP-04' }],
  },
]

export const COLETAS_TMS: ColetaTms[] = [
  {
    id: 'COL-4421',
    viagemIdTms: 'TMS-VIA-88012',
    cotacaoId: 'COT-5518',
    transportadora: 'Correios',
    rota: 'SP-Capital',
    veiculo: 'Van',
    placa: 'PLT-2D45',
    tipoVeiculo: 'Van leve',
    capacidadeKg: 650,
    capacidadeVolumes: 180,
    doca: 'DOCA-03',
    janelaColeta: '10:00-10:30',
    cutOff: '09:45',
    status: 'carregando',
    risco: 'medio',
    pedidos: ['PED-77119', 'PED-77120', 'PED-77121'],
    ondaId: 'OND-501',
    romaneioId: 'ROM-3301',
    volumesPrevistos: 3,
    volumesProntos: 2,
    pesoPrevisto: 1.9,
    pesoPronto: 1.5,
    progressoPicking: 88,
    progressoPacking: 67,
    progressoCarregamento: 50,
    ultimaMensagemTms: 'Veículo confirmado pelo TMS. Motorista autorizado a encostar na doca 03.',
  },
  {
    id: 'COL-4422',
    viagemIdTms: 'TMS-VIA-88013',
    cotacaoId: 'COT-5520',
    transportadora: 'Jamef',
    rota: 'Interior-SP',
    veiculo: 'Truck',
    placa: 'JKM-9981',
    tipoVeiculo: 'Truck baú',
    capacidadeKg: 3500,
    capacidadeVolumes: 720,
    doca: 'DOCA-04',
    janelaColeta: '12:00-12:40',
    cutOff: '11:30',
    status: 'validando',
    risco: 'alto',
    pedidos: ['PED-77122'],
    ondaId: 'OND-502',
    romaneioId: 'ROM-3302',
    volumesPrevistos: 3,
    volumesProntos: 0,
    pesoPrevisto: 18.5,
    pesoPronto: 0,
    progressoPicking: 0,
    progressoPacking: 0,
    progressoCarregamento: 0,
    ultimaMensagemTms: 'Aguardando confirmação de reserva total antes de liberar onda de separação.',
  },
  {
    id: 'COL-4423',
    viagemIdTms: 'TMS-VIA-88014',
    cotacaoId: 'COT-5523',
    transportadora: 'Rápido Brasil',
    rota: 'RJ-Capital',
    veiculo: 'Toco',
    placa: 'RBR-4J91',
    tipoVeiculo: 'Toco baú',
    capacidadeKg: 4200,
    capacidadeVolumes: 860,
    doca: 'DOCA-05',
    janelaColeta: '15:00-15:45',
    cutOff: '14:15',
    status: 'recebida',
    risco: 'baixo',
    pedidos: ['PED-77130', 'PED-77131'],
    ondaId: 'OND-503',
    romaneioId: 'ROM-3303',
    volumesPrevistos: 12,
    volumesProntos: 0,
    pesoPrevisto: 164,
    pesoPronto: 0,
    progressoPicking: 0,
    progressoPacking: 0,
    progressoCarregamento: 0,
    ultimaMensagemTms: 'Coleta criada no TMS e aguardando validação do WMS.',
  },
]

export const CROSSDOCK = [
  { id: 'XD-01', sku: 'SKU-30011', descricao: 'Azeite Extra Virgem 500ml', recebimento: 'REC-2042', docaEntrada: ADMIN_BUSINESS_DOCAS.recebimento01, docaSaida: ADMIN_BUSINESS_DOCAS.mista04, quantidade: 48, destino: 'CD Duque de Caxias', status: 'aguardando-triagem' },
  { id: 'XD-02', sku: 'SKU-20055', descricao: 'Sérum Vitamina C 30ml', recebimento: 'REC-2040', docaEntrada: ADMIN_BUSINESS_DOCAS.recebimento02, docaSaida: ADMIN_BUSINESS_DOCAS.expedicao03, quantidade: 60, destino: 'Loja Bella Centro', status: 'em-transito-interno' },
]

export const ENDERECOS_SUGESTOES = [...ADMIN_BUSINESS_ENDERECOS_SUGESTOES]
