import type {
  DemoAddress,
  DemoAppResponsibility,
  DemoChecklistTemplate,
  DemoDevice,
  DemoEffectiveParameter,
  DemoOperationalEvent,
  DemoOperationalOccurrence,
  DemoOccurrenceReason,
  DemoOperationalTask,
  DemoOwner,
  DemoProfile,
  DemoSku,
  DemoUser,
  DemoWarehouse,
} from './types'

export const DEMO_WAREHOUSES: DemoWarehouse[] = [
  { id: 'cd-sp', codigo: 'CD-SP', nome: 'CD Cajamar', cidade: 'Cajamar', uf: 'SP', modo: 'completo', ativo: true },
  { id: 'cd-rj', codigo: 'CD-RJ', nome: 'CD Duque de Caxias', cidade: 'Duque de Caxias', uf: 'RJ', modo: 'completo', ativo: true },
  { id: 'lj-pe', codigo: 'LJ-PE', nome: 'Loja Jaboatao', cidade: 'Jaboatao dos Guararapes', uf: 'PE', modo: 'simples', ativo: true },
]

export const DEMO_OWNERS: DemoOwner[] = [
  { id: 'own-nano', codigo: 'NANO', nome: 'NanoTech Eletronicos', cnpj: '12.345.678/0001-90', cor: '#2563eb', ativo: true },
  { id: 'own-bella', codigo: 'BELLA', nome: 'Bella Cosmeticos', cnpj: '23.456.789/0001-01', cor: '#db2777', ativo: true },
  { id: 'own-verde', codigo: 'VERDE', nome: 'Verde Alimentos', cnpj: '34.567.890/0001-12', cor: '#16a34a', ativo: true },
  { id: 'own-forte', codigo: 'FORTE', nome: 'Forte Industria', cnpj: '45.678.901/0001-23', cor: '#f97316', ativo: true },
]

export const DEMO_SKUS: DemoSku[] = [
  {
    id: 'sku-10241',
    codigo: 'SKU-10241',
    ean: '7891000102413',
    descricao: 'Fone Bluetooth Pulse X',
    categoria: 'Eletronicos',
    curva: 'A',
    unidade: 'UN',
    unidadesPorCaixa: 6,
    peso: 0.18,
    altura: 8,
    largura: 18,
    profundidade: 20,
    controleLote: false,
    controleValidade: false,
    controleSerie: true,
    ncm: '8518.30.00',
    cest: '21.106.00',
    origem: 2,
    ownerId: 'own-nano',
    ativo: true,
  },
  {
    id: 'sku-10242',
    codigo: 'SKU-10242',
    ean: '7891000102420',
    descricao: 'Carregador Turbo 30W',
    categoria: 'Eletronicos',
    curva: 'A',
    unidade: 'UN',
    unidadesPorCaixa: 10,
    peso: 0.12,
    altura: 6,
    largura: 10,
    profundidade: 12,
    controleLote: false,
    controleValidade: false,
    controleSerie: false,
    ncm: '8504.40.21',
    cest: '21.107.00',
    origem: 2,
    ownerId: 'own-nano',
    ativo: true,
  },
  {
    id: 'sku-10243',
    codigo: 'SKU-10243',
    ean: '7891000102437',
    descricao: 'Cabo USB-C 2m',
    categoria: 'Eletronicos',
    curva: 'A',
    unidade: 'UN',
    unidadesPorCaixa: 12,
    peso: 0.05,
    altura: 2,
    largura: 12,
    profundidade: 14,
    controleLote: false,
    controleValidade: false,
    controleSerie: false,
    ncm: '8544.42.00',
    cest: '21.107.00',
    origem: 2,
    ownerId: 'own-nano',
    ativo: true,
  },
  {
    id: 'sku-10244',
    codigo: 'SKU-10244',
    ean: '7891000102444',
    descricao: 'Power Bank 10000mAh',
    categoria: 'Eletronicos',
    curva: 'A',
    unidade: 'UN',
    unidadesPorCaixa: 8,
    peso: 0.22,
    altura: 2,
    largura: 7,
    profundidade: 14,
    controleLote: false,
    controleValidade: false,
    controleSerie: true,
    ncm: '8507.60.00',
    cest: '21.108.00',
    origem: 2,
    ownerId: 'own-nano',
    ativo: true,
  },
  {
    id: 'sku-20055',
    codigo: 'SKU-20055',
    ean: '7892000200557',
    descricao: 'Serum Vitamina C 30ml',
    categoria: 'Cosmeticos',
    curva: 'B',
    unidade: 'UN',
    unidadesPorCaixa: 24,
    peso: 0.09,
    altura: 12,
    largura: 4,
    profundidade: 4,
    controleLote: true,
    controleValidade: true,
    controleSerie: false,
    ncm: '3304.99.90',
    cest: '20.045.00',
    origem: 0,
    ownerId: 'own-bella',
    ativo: true,
  },
  {
    id: 'sku-30011',
    codigo: 'SKU-30011',
    ean: '7893000300117',
    descricao: 'Azeite Extra Virgem 500ml',
    categoria: 'Alimentos',
    curva: 'B',
    unidade: 'UN',
    unidadesPorCaixa: 12,
    peso: 0.54,
    altura: 26,
    largura: 6,
    profundidade: 6,
    controleLote: true,
    controleValidade: true,
    controleSerie: false,
    ncm: '1509.20.00',
    cest: '17.063.00',
    origem: 0,
    ownerId: 'own-verde',
    ativo: true,
  },
  {
    id: 'sku-30012',
    codigo: 'SKU-30012',
    ean: '7893000300124',
    descricao: 'Grao de Bico 1kg',
    categoria: 'Alimentos',
    curva: 'C',
    unidade: 'UN',
    unidadesPorCaixa: 12,
    peso: 1,
    altura: 6,
    largura: 18,
    profundidade: 26,
    controleLote: true,
    controleValidade: true,
    controleSerie: false,
    ncm: '0713.20.90',
    cest: '17.056.00',
    origem: 0,
    ownerId: 'own-verde',
    ativo: true,
  },
  {
    id: 'mp-7781',
    codigo: 'MP-7781',
    ean: '7894000407819',
    descricao: 'Resina PET grau A',
    categoria: 'Industrial',
    curva: 'C',
    unidade: 'SC',
    unidadesPorCaixa: 1,
    peso: 25,
    altura: 14,
    largura: 50,
    profundidade: 80,
    controleLote: true,
    controleValidade: true,
    controleSerie: false,
    ncm: '3907.61.00',
    cest: '',
    origem: 0,
    ownerId: 'own-forte',
    ativo: true,
  },
]

export const DEMO_ADDRESSES: DemoAddress[] = [
  { codigo: 'A-12-03-2', armazemId: 'cd-sp', zona: 'PICK-A', tipo: 'picking', bloqueado: false },
  { codigo: 'A-12-04-1', armazemId: 'cd-sp', zona: 'PICK-A', tipo: 'picking', bloqueado: false },
  { codigo: 'A-13-01-1', armazemId: 'cd-sp', zona: 'PICK-A', tipo: 'picking', bloqueado: false },
  { codigo: 'B-04-12-3', armazemId: 'cd-sp', zona: 'PULM-A', tipo: 'pulmao', bloqueado: false },
  { codigo: 'C-08-01-1', armazemId: 'cd-sp', zona: 'ALIM-A', tipo: 'picking', bloqueado: false },
  { codigo: 'D-01-01-1', armazemId: 'cd-sp', zona: 'QUALI', tipo: 'quarentena', bloqueado: false },
  { codigo: 'PADRAO', armazemId: 'lj-pe', zona: 'LOJA', tipo: 'picking', bloqueado: false },
]

export const DEMO_PROFILES: DemoProfile[] = [
  { id: 'perf-op', nome: 'Operador', cor: '#64748b', permissoes: ['picking.executar', 'recebimento.conferir'] },
  { id: 'perf-sup', nome: 'Supervisor', cor: '#2563eb', permissoes: ['tarefa.atribuir', 'inventario.aprovar', 'ocorrencia.tratar'] },
  { id: 'perf-ges', nome: 'Gestor', cor: '#00a88e', permissoes: ['onda.liberar', 'relatorio.visualizar', 'expedicao.priorizar'] },
  { id: 'perf-adm', nome: 'Administrador', cor: '#7c3aed', permissoes: ['config.editar', 'perfil.gerenciar', 'usuario.gerenciar'] },
]

export const DEMO_USERS: DemoUser[] = [
  { id: 'usr-1', nome: 'Carlos Mendes', email: 'carlos.mendes@integra.com.br', perfilId: 'perf-op', armazemIds: ['cd-sp'], ativo: true },
  { id: 'usr-2', nome: 'Ana Paula Souza', email: 'ana.souza@integra.com.br', perfilId: 'perf-sup', armazemIds: ['cd-sp', 'cd-rj'], ativo: true },
  { id: 'usr-3', nome: 'Roberto Lima', email: 'roberto.lima@integra.com.br', perfilId: 'perf-ges', armazemIds: ['cd-sp', 'cd-rj', 'lj-pe'], ownerIds: ['own-nano', 'own-bella', 'own-verde'], ativo: true },
  { id: 'usr-4', nome: 'Admin Demo', email: 'admin@integra.com.br', perfilId: 'perf-adm', armazemIds: ['cd-sp', 'cd-rj', 'lj-pe'], ativo: true },
]

export const DEMO_OCCURRENCE_REASONS: DemoOccurrenceReason[] = [
  { id: 'falta', codigo: 'FALTA', rotulo: 'Faltou', tipo: 'falta', exigeAprovacao: true, bloqueiaFluxo: true, cor: '#E02424' },
  { id: 'sobra', codigo: 'SOBRA', rotulo: 'Sobrou', tipo: 'sobra', exigeAprovacao: true, bloqueiaFluxo: true, cor: '#E08A00' },
  { id: 'avaria', codigo: 'AVARIA', rotulo: 'Avariado', tipo: 'avaria', exigeFoto: true, bloqueiaFluxo: true, cor: '#E02424' },
  { id: 'local-cheio', codigo: 'LCHEIO', rotulo: 'Local cheio', tipo: 'local-cheio', bloqueiaFluxo: true, cor: '#E08A00' },
  { id: 'local-vazio', codigo: 'LVAZIO', rotulo: 'Local vazio', tipo: 'local-vazio', exigeFoto: true, bloqueiaFluxo: true, cor: '#7A8199' },
  { id: 'item-trocado', codigo: 'TROCADO', rotulo: 'Item trocado', tipo: 'item-trocado', exigeAprovacao: true, bloqueiaFluxo: true, cor: '#7C3AED' },
]

export const DEMO_EFFECTIVE_PARAMETERS: DemoEffectiveParameter[] = [
  {
    chave: 'conferencia_cega',
    grupo: 'Recebimento',
    label: 'Conferencia cega',
    descricao: 'Operador conta sem ver a quantidade esperada.',
    valor: 'true',
    valorLabel: 'Ativa',
    origem: 'global',
    escopoLabel: 'Global',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-frontend', 'wms-mobile'],
  },
  {
    chave: 'fefo_obrigatorio',
    grupo: 'Enderecamento',
    label: 'FEFO obrigatorio',
    descricao: 'Picking e reabastecimento respeitam o lote de menor validade.',
    valor: 'true',
    valorLabel: 'Ativo para alimentos e cosmeticos',
    origem: 'owner',
    escopoLabel: 'Owner Verde Alimentos',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-frontend', 'wms-mobile'],
  },
  {
    chave: 'enderecamento_caotico',
    grupo: 'Enderecamento',
    label: 'Enderecamento caotico',
    descricao: 'Sugestao dinamica de destino baseada em disponibilidade e regras.',
    valor: 'true',
    valorLabel: 'Ativo no CD Cajamar',
    origem: 'cd',
    escopoLabel: 'CD Cajamar',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-frontend', 'wms-mobile'],
  },
  {
    chave: 'interleaving',
    grupo: 'Picking e ondas',
    label: 'Interleaving',
    descricao: 'O sistema encaixa uma tarefa no caminho de retorno do operador.',
    valor: 'true',
    valorLabel: 'Ativo',
    origem: 'global',
    escopoLabel: 'Global',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-frontend', 'wms-mobile'],
  },
  {
    chave: 'offline_first',
    grupo: 'Dispositivos',
    label: 'Modo offline-first',
    descricao: 'O coletor segue operando sem Wi-Fi e sincroniza depois.',
    valor: 'true',
    valorLabel: 'Ativo nos coletores Zebra',
    origem: 'global',
    escopoLabel: 'Global',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-mobile'],
  },
  {
    chave: 'controle_serie_global',
    grupo: 'Controles',
    label: 'Controle por serie',
    descricao: 'Obrigatorio em itens de alto valor e eletronicos.',
    valor: 'true',
    valorLabel: 'Ativo para NanoTech',
    origem: 'owner',
    escopoLabel: 'Owner NanoTech',
    gerenciadoPor: 'wms-admin-business',
    consumidoPor: ['wms-frontend', 'wms-mobile'],
  },
]

export const DEMO_DEVICES: DemoDevice[] = [
  { id: 'dev-1', nome: 'Coletor Zebra TC21', tipo: 'coletor', status: 'online', operador: 'Carlos Mendes', armazemId: 'cd-sp' },
  { id: 'dev-2', nome: 'Coletor Zebra TC26', tipo: 'coletor', status: 'online', operador: 'Ana Paula Souza', armazemId: 'cd-sp' },
  { id: 'dev-3', nome: 'Voice Headset 04', tipo: 'voice', status: 'offline', operador: 'Marina Costa', armazemId: 'cd-rj' },
]

export const DEMO_OPERATIONAL_TASKS: DemoOperationalTask[] = [
  {
    id: 'T-9003',
    fluxo: 'separar',
    prioridade: 'alta',
    status: 'IN_PROGRESS',
    resumo: 'Pedido #4471 - 3 itens',
    contexto: 'Onda 12 · Rota Sul · owner NanoTech',
    conclusao: 'Leve o pedido a area de conferencia.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'A-12-03-2',
    destino: 'PACK-01',
    skuCodigo: 'SKU-10241',
    quantidadeBase: 12,
    passos: [
      { instrucao: 'Va ate o endereco', esperado: 'A-12-03-2', rotulo: 'Endereco', tipo: 'scan', icon: 'location' },
      { instrucao: 'Bipe o produto', esperado: 'SKU-10241', rotulo: 'Produto', tipo: 'scan', icon: 'cube', dica: 'Fone Bluetooth Pulse X · caixa com 6' },
      { instrucao: 'Pegue e confirme', esperado: '2', rotulo: 'Quantidade', tipo: 'quantidade', icon: 'layers', unidade: 'cx', fatorBase: 6 },
    ],
  },
  {
    id: 'T-9011',
    fluxo: 'receber',
    prioridade: 'normal',
    status: 'ASSIGNED',
    resumo: 'Doca 03 - Recebimento NanoTech',
    contexto: 'NF-e 88.214 · conferencia cega',
    conclusao: 'Mercadoria liberada para staging a enderecar.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'DOCA-03',
    destino: 'STG-REC-03',
    skuCodigo: 'SKU-10241',
    quantidadeBase: 120,
    passos: [
      { instrucao: 'Bipe a doca', esperado: 'DOCA-03', rotulo: 'Doca', tipo: 'scan', icon: 'car' },
      { instrucao: 'Bipe o produto', esperado: 'SKU-10241', rotulo: 'Produto', tipo: 'scan', icon: 'cube', dica: 'Fone Bluetooth Pulse X · caixa com 12' },
      { instrucao: 'Conte as caixas', esperado: '10', rotulo: 'Caixas recebidas', tipo: 'quantidade', icon: 'calculator', unidade: 'cx', fatorBase: 12 },
    ],
  },
  {
    id: 'T-9001',
    fluxo: 'guardar',
    prioridade: 'normal',
    status: 'ASSIGNED',
    resumo: 'Palete SSCC-7781',
    contexto: 'Sugestao do sistema para CD Cajamar',
    conclusao: 'Estoque agora disponivel para venda.',
    ownerId: 'own-bella',
    armazemId: 'cd-sp',
    origem: 'STG-REC-03',
    destino: 'B-04-12-3',
    skuCodigo: 'SKU-20055',
    quantidadeBase: 300,
    passos: [
      { instrucao: 'Bipe o palete', esperado: 'SSCC-7781', rotulo: 'Palete', tipo: 'scan', icon: 'file-tray-stacked' },
      { instrucao: 'Guarde e bipe o local', esperado: 'B-04-12-3', rotulo: 'Endereco destino', tipo: 'scan', icon: 'location' },
    ],
  },
  {
    id: 'T-9005',
    fluxo: 'abastecer',
    prioridade: 'normal',
    status: 'ASSIGNED',
    resumo: 'Repor picking A-13-01-1',
    contexto: 'Abaixo do minimo · owner NanoTech',
    conclusao: 'Endereco de picking reabastecido.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'PUL-A-22',
    destino: 'A-13-01-1',
    skuCodigo: 'SKU-10243',
    quantidadeBase: 144,
    passos: [
      { instrucao: 'Bipe o pulmao (origem)', esperado: 'PUL-A-22', rotulo: 'Origem', tipo: 'scan', icon: 'arrow-up-circle' },
      { instrucao: 'Bipe o picking (destino)', esperado: 'A-13-01-1', rotulo: 'Destino', tipo: 'scan', icon: 'arrow-down-circle' },
      { instrucao: 'Confirme a quantidade', esperado: '12', rotulo: 'Quantidade', tipo: 'quantidade', icon: 'layers', unidade: 'cx', fatorBase: 12 },
    ],
  },
  {
    id: 'T-9006',
    fluxo: 'contar',
    prioridade: 'normal',
    status: 'ASSIGNED',
    resumo: 'Contagem cega A-12-03-2',
    contexto: 'Inventario rotativo · curva A',
    conclusao: 'Contagem registrada. Divergencia vai para aprovacao.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'A-12-03-2',
    destino: 'A-12-03-2',
    skuCodigo: 'SKU-10241',
    quantidadeBase: 84,
    passos: [
      { instrucao: 'Bipe o endereco', esperado: 'A-12-03-2', rotulo: 'Endereco', tipo: 'scan', icon: 'location', dica: 'Fone Bluetooth Pulse X · caixa com 6' },
      { instrucao: 'Conte o que esta no local', esperado: '84', rotulo: 'Contagem do endereco', tipo: 'quantidade', icon: 'calculator', unidade: 'cx', fatorBase: 6, contagemMista: true },
    ],
  },
  {
    id: 'T-9010',
    fluxo: 'conferir',
    prioridade: 'alta',
    status: 'ASSIGNED',
    resumo: 'Conferir saida - Pedido #4471',
    contexto: 'Ultima barreira antes do envio',
    conclusao: 'Pedido conferido. Liberado para packing.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'PACK-01',
    destino: 'DOCA-03',
    skuCodigo: 'SKU-10241',
    quantidadeBase: 12,
    passos: [
      { instrucao: 'Bipe o volume', esperado: 'VOL-4471-1', rotulo: 'Volume', tipo: 'scan', icon: 'cube' },
      { instrucao: 'Bipe cada item', esperado: 'SKU-10241', rotulo: 'Produto', tipo: 'scan', icon: 'barcode' },
      { instrucao: 'Confirme', esperado: 'OK', rotulo: 'Conferencia', tipo: 'confirmar', icon: 'checkmark-done' },
    ],
  },
  {
    id: 'T-9012',
    fluxo: 'carregar',
    prioridade: 'alta',
    status: 'ASSIGNED',
    resumo: 'Carregar ROM-3301',
    contexto: 'Coleta COL-4421 · Correios · DOCA-03',
    conclusao: 'Volume carregado. Romaneio atualizado para o TMS.',
    ownerId: 'own-nano',
    armazemId: 'cd-sp',
    origem: 'STG-EXP-03',
    destino: 'DOCA-03',
    skuCodigo: 'VOL-77120-1',
    quantidadeBase: 1,
    passos: [
      { instrucao: 'Bipe a doca', esperado: 'DOCA-03', rotulo: 'Doca', tipo: 'scan', icon: 'business' },
      { instrucao: 'Bipe a placa', esperado: 'PLT-2D45', rotulo: 'Veiculo', tipo: 'scan', icon: 'car' },
      { instrucao: 'Bipe o volume', esperado: 'VOL-77120-1', rotulo: 'Volume', tipo: 'scan', icon: 'cube' },
      { instrucao: 'Confirme o lacre', esperado: 'LCR-8842', rotulo: 'Lacre', tipo: 'scan', icon: 'lock-closed' },
      { instrucao: 'Finalizar embarque', esperado: 'OK', rotulo: 'Carregamento', tipo: 'confirmar', icon: 'checkmark-done' },
    ],
  },
]

export const DEMO_CHECKLIST_TEMPLATES: DemoChecklistTemplate[] = [
  {
    id: 'chk-rec-chegada-v1',
    code: 'REC-CHEGADA',
    name: 'Checklist de chegada e conferencia',
    flow: 'receber',
    warehouseId: 'cd-sp',
    ownerId: null,
    active: true,
    version: 1,
    blocksOnFailure: true,
    questions: [
      {
        id: 'rec-produto-correto',
        text: 'Produto recebido confere com NF/OS?',
        type: 'OK_NOK_NA',
        required: true,
        okLabel: 'Produto correto',
        failLabel: 'Produto divergente',
        failValues: ['NOK'],
        requiresObservationOnFail: true,
        blocksStep: true,
        requiresSupervisor: true,
      },
      {
        id: 'rec-embalagem',
        text: 'Embalagem esta integra para seguir a conferencia?',
        type: 'OK_NOK_NA',
        required: true,
        okLabel: 'Embalagem integra',
        failLabel: 'Embalagem avariada',
        failValues: ['NOK'],
        requiresPhotoOnFail: true,
        requiresObservationOnFail: true,
        blocksStep: true,
      },
      {
        id: 'rec-lacre-validade',
        text: 'Lacre, lote e validade estao legiveis?',
        type: 'OK_NOK_NA',
        required: true,
        okLabel: 'Dados legiveis',
        failLabel: 'Dado ilegivel',
        failValues: ['NOK'],
        requiresPhotoOnFail: true,
        requiresObservationOnFail: true,
        requiresSupervisor: true,
      },
    ],
  },
  {
    id: 'chk-sep-picking-v1',
    code: 'PICK-ENDERECO',
    name: 'Checklist de picking no endereco',
    flow: 'separar',
    warehouseId: 'cd-sp',
    ownerId: null,
    active: true,
    version: 1,
    blocksOnFailure: true,
    questions: [
      {
        id: 'sep-produto',
        text: 'Produto fisico confere com a OS?',
        type: 'OK_NOK_NA',
        required: true,
        okLabel: 'Produto correto',
        failLabel: 'Produto divergente',
        failValues: ['NOK'],
        requiresObservationOnFail: true,
        blocksStep: true,
      },
      {
        id: 'sep-endereco-vazio',
        text: 'Existe produto fisico no endereco?',
        type: 'BOOLEAN',
        required: true,
        okLabel: 'Produto encontrado',
        failLabel: 'Endereco vazio',
        failValues: ['NO'],
        requiresPhotoOnFail: true,
        requiresObservationOnFail: true,
        blocksStep: true,
      },
    ],
  },
  {
    id: 'chk-car-veiculo-v1',
    code: 'EXP-VEICULO',
    name: 'Checklist de embarque e veiculo',
    flow: 'carregar',
    warehouseId: 'cd-sp',
    ownerId: null,
    active: true,
    version: 1,
    blocksOnFailure: true,
    questions: [
      {
        id: 'car-doca',
        text: 'Veiculo esta na doca correta?',
        type: 'BOOLEAN',
        required: true,
        okLabel: 'Doca correta',
        failLabel: 'Doca errada',
        failValues: ['NO'],
        requiresPhotoOnFail: true,
        requiresObservationOnFail: true,
        blocksStep: true,
      },
      {
        id: 'car-lacre',
        text: 'Lacre confere antes de finalizar?',
        type: 'BOOLEAN',
        required: true,
        okLabel: 'Lacre confere',
        failLabel: 'Lacre diverge',
        failValues: ['NO'],
        requiresObservationOnFail: true,
        requiresSupervisor: true,
        blocksStep: true,
      },
    ],
  },
  {
    id: 'chk-putaway-v1',
    code: 'PUTAWAY-PALLET',
    name: 'Checklist de put-away dirigido',
    flow: 'guardar',
    warehouseId: 'cd-sp',
    ownerId: null,
    active: true,
    version: 1,
    blocksOnFailure: true,
    questions: [
      {
        id: 'gua-etiqueta',
        text: 'Palete esta identificado com etiqueta legivel?',
        type: 'OK_NOK_NA',
        required: true,
        okLabel: 'Palete identificado',
        failLabel: 'Sem etiqueta',
        failValues: ['NOK'],
        requiresPhotoOnFail: true,
        requiresObservationOnFail: true,
        blocksStep: true,
      },
      {
        id: 'gua-capacidade',
        text: 'Endereco destino comporta a unidade logistica?',
        type: 'BOOLEAN',
        required: true,
        okLabel: 'Endereco comporta',
        failLabel: 'Nao comporta',
        failValues: ['NO'],
        requiresObservationOnFail: true,
        blocksStep: true,
      },
    ],
  },
]

export const DEMO_OPERATIONAL_OCCURRENCES: DemoOperationalOccurrence[] = [
  {
    id: 'OCC-7001',
    warehouseId: 'cd-sp',
    ownerId: 'own-nano',
    type: 'avaria',
    severity: 'HIGH',
    status: 'BLOCKING_FLOW',
    sourceFlow: 'receber',
    sourceTaskId: 'T-9011',
    sourceDocumentId: 'NF-e 88.214',
    productId: 'SKU-10241',
    locationId: 'DOCA-03',
    reasonCodeId: 'avaria',
    title: 'Embalagem avariada no recebimento',
    description: 'Operador reprovou pergunta bloqueante do checklist de chegada. Foto anexada e OS aguardando decisao do lider.',
    blocksFlow: true,
    blocksStock: true,
    assignedTo: null,
    dueAt: '2026-06-26T10:15:00-03:00',
    createdBy: 'usr-1',
    createdAt: '2026-06-26T09:42:00-03:00',
    resolvedAt: null,
    resolutionCode: null,
    evidence: [
      {
        id: 'att-7001',
        type: 'PHOTO',
        label: 'Foto da embalagem lateral direita',
        capturedBy: 'usr-1',
        capturedAt: '2026-06-26T09:41:00-03:00',
        deviceId: 'dev-1',
      },
    ],
  },
  {
    id: 'OCC-7002',
    warehouseId: 'cd-sp',
    ownerId: 'own-nano',
    type: 'local-vazio',
    severity: 'MEDIUM',
    status: 'WAITING_SUPERVISOR',
    sourceFlow: 'separar',
    sourceTaskId: 'T-9003',
    sourceDocumentId: 'Onda 12',
    productId: 'SKU-10241',
    locationId: 'A-12-03-2',
    reasonCodeId: 'local-vazio',
    title: 'Endereco vazio no picking',
    description: 'Separador registrou endereco sem produto fisico. Necessario recontar posicao ou realocar pick.',
    blocksFlow: true,
    blocksStock: false,
    assignedTo: 'Ana Paula Souza',
    dueAt: '2026-06-26T10:00:00-03:00',
    createdBy: 'usr-1',
    createdAt: '2026-06-26T09:20:00-03:00',
    resolvedAt: null,
    resolutionCode: null,
    evidence: [],
  },
]

export const DEMO_OPERATIONAL_EVENTS: DemoOperationalEvent[] = [
  {
    id: 'evt-9001',
    objectType: 'task',
    objectId: 'T-9011',
    eventType: 'task.assigned',
    message: 'Tarefa atribuida ao operador Carlos Mendes.',
    userId: 'usr-2',
    timestamp: '2026-06-26T09:35:00-03:00',
  },
  {
    id: 'evt-9002',
    objectType: 'occurrence',
    objectId: 'OCC-7001',
    eventType: 'checklist.failed',
    message: 'Pergunta bloqueante reprovada: embalagem avariada.',
    payload: { taskId: 'T-9011', questionId: 'rec-embalagem', blocksFlow: true },
    userId: 'usr-1',
    timestamp: '2026-06-26T09:42:00-03:00',
  },
  {
    id: 'evt-9003',
    objectType: 'occurrence',
    objectId: 'OCC-7002',
    eventType: 'occurrence.created',
    message: 'Endereco vazio registrado no picking.',
    payload: { taskId: 'T-9003', locationId: 'A-12-03-2' },
    userId: 'usr-1',
    timestamp: '2026-06-26T09:20:00-03:00',
  },
]

export const DEMO_APP_RESPONSIBILITIES: DemoAppResponsibility[] = [
  {
    tela: 'Parametros',
    app: 'wms-admin-business',
    classificacao: 'admin',
    papel: 'Governanca da operacao',
    acaoEsperada: 'Definir regras que frontend e mobile apenas consomem.',
  },
  {
    tela: 'Usuarios e Perfis',
    app: 'wms-admin-business',
    classificacao: 'admin',
    papel: 'Acesso e alcada',
    acaoEsperada: 'Definir quem pode aprovar ajuste, liberar onda e tratar ocorrencia.',
  },
  {
    tela: 'Configuracoes',
    app: 'wms-frontend',
    classificacao: 'frontend-supervisor',
    papel: 'Consulta operacional',
    acaoEsperada: 'Exibir regras vigentes e o app responsavel pela edicao.',
  },
  {
    tela: 'Fila de tarefas',
    app: 'wms-frontend',
    classificacao: 'frontend-supervisor',
    papel: 'Orquestracao',
    acaoEsperada: 'Atribuir, priorizar e acompanhar tarefas de operadores.',
  },
  {
    tela: 'Coletor RF',
    app: 'wms-frontend',
    classificacao: 'demo',
    papel: 'Simulacao comercial',
    acaoEsperada: 'Demonstrar o conceito do scan-to-confirm sem assumir o lugar do mobile.',
  },
  {
    tela: 'FlowScreen',
    app: 'wms-mobile',
    classificacao: 'mobile-operador',
    papel: 'Execucao do operador',
    acaoEsperada: 'Bipar, confirmar quantidade e registrar problema sem sair do fluxo.',
  },
]
